In [2]:
import numpy as np

In [3]:
import random 

In [4]:
###ex1
A = np.array([[1,2,3],
              [2,4,1],
              [3,1,0]])

print(" le rang est :",np.linalg.matrix_rank(A),"\n",
      "le determinant :",np.linalg.det(A),"\n",
      "la trace :",np.trace(A),"\n",
      "4 + 1 + 0 =",4+1+0,"\n",
      "les valeurs propres de A :",np.linalg.eigvals(A)
      ,"\n",
      "la somme des valeurs propres :",sum(np.linalg.eigvals(A)),"\n")
for i in np.linalg.eigvals(A):   
    print("verification det(landa*I_n - A) :",np.linalg.det((i*np.eye(3))-A),"\n")
    
    
    
(x,y)=np.linalg.eig(A) 



y = np.transpose(y)


for i in range(3):
    vp = np.transpose(y[i])
    print( np.dot(A,vp), x[i]*vp,"\n")
    
    
D = np.eye(3)

for i in range(3):
    D[i][i]= np.linalg.eigvals(A)[i]
    
print(np.dot(np.dot(np.transpose(y),D),np.linalg.inv(np.transpose(y))))


 le rang est : 3 
 le determinant : -25.000000000000007 
 la trace : 5 
 4 + 1 + 0 = 5 
 les valeurs propres de A : [ 5.97344343 -2.58959802  1.61615459] 
 la somme des valeurs propres : 5.000000000000005 

verification det(landa*I_n - A) : 1.8212195514918646e-13 

verification det(landa*I_n - A) : 7.695247105675758e-15 

verification det(landa*I_n - A) : 9.816722705639634e-15 

[-3.21201905 -4.45018175 -2.35814385] [-3.21201905 -4.45018175 -2.35814385] 

[ 1.72953303 -0.23461749 -1.91303112] [ 1.72953303 -0.23461749 -1.91303112] 

[ 0.83165445 -1.06809972  0.88287571] [ 0.83165445 -1.06809972  0.88287571] 

[[1.00000000e+00 2.00000000e+00 3.00000000e+00]
 [2.00000000e+00 4.00000000e+00 1.00000000e+00]
 [3.00000000e+00 1.00000000e+00 1.12544347e-15]]


In [5]:
np.linalg.matrix_rank?

In [6]:
np.linalg.det?

In [15]:
np.trace?

In [28]:
np.linalg.eigvals?

In [29]:
np.eye(3)-np.eye(3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.linalg.eig?

In [7]:
A=np.transpose(A)
A

array([[1, 2, 3],
       [2, 4, 1],
       [3, 1, 0]])

In [8]:
A = np.array([[1,2,3],
              [2,4,1],
              [3,1,0]])


In [9]:
def norme(x):
    return max([max(x),abs(min(x))])
               
#print(norme(np.array([1,-8,5])))

def f(b,A):
    return (1/norme(np.dot(b,A)))*np.dot(b,A)

def puissanceIteree(A,k):
    b0= [np.random.random_sample() for i in range(len(A))]
    i = 1
    while i<k:
        b0 = f(b0,A)
        i+=1
    return b0

def vecteurPropre(A ,eps):
    b0= [np.random.random_sample() for i in range(len(A))]
    bk= f(b0,A)
    while norme(b0-bk)>eps or norme(b0+bk)>eps:
        b0=bk
        bk = f(bk,A)
    return b0





In [16]:
np.random.random_sample?